# Generated by Django 3.2.4 on 2021-07-03 06:01

from django.db import migrations
from ..utils.seed import seed_data


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            seed_data, reverse_code=migrations.RunPython.noop),
    ]
